spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/track_expenses?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  thymeleaf:
    # 在構建URL時用於檢視名稱的字首，預設為classpath:/templates/
    prefix: classpath:/templates/
    # 在構建URL時附加到檢視名稱的字尾，預設為.html
    suffix: .html
    # 模板模式，預設為HTML
    mode: HTML
    # 模板檔案編碼，預設為UTF-8
    encoding: UTF-8
    # 是否啟用模板快取，預設為true，表示啟用，false不啟用
    cache: false
    # 在呈現模板之前是否檢查模板存在與否，預設為true
    check-template: true
    # 是否檢查模板位置存在與否，預設為true
    check-template-location: true  